version: "1.0"
services:
  backend:
    image: brandonrafaellovelyno/outfit-ai-be:1.1
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production

  frontend:
    image: brandonrafaellovelyno/outfit-ai-fe:1.0
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
